TravelTripProje/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTripProje.Models.Siniflar;

namespace TravelTripProje.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default

        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Blogs.ToList();
            return View(degerler);
        }

        public ActionResult Contact()
        {
            return View();
        }

        public PartialViewResult Partial1()
        {
            var deger = c.Blogs.Take(10).ToList();
            return PartialView(deger);
        }

        public PartialViewResult Partial2()
        {
            var deger2 = c.Blogs.Take(3).ToList();
            return PartialView(deger2);
        }

        public PartialViewResult Partial3()
        {
            var deger3 = c.Blogs.Take(3).OrderByDescending(x=>x.ID).ToList();
            return PartialView(deger3);
        }
    }
}

TravelTripProje/Views/Default/Index.cshtml
@using TravelTripProje.Models.Siniflar;
@model List<Blog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Test.cshtml";
}

<div class="header-banner">
    <div class="wrap">
        <div class="banner">
            <div class="indent">
                <h2 class="indent-left margin-bot">Tatil & Seyhat Bloğum</h2>
                <div class="banner-left">
                    <div class="con-text">
                        <div class="grid1-img">
                            <img src="~/web/images/glass.png" alt="">
                        </div>
                        <div class="grid1-desc">
                            <p>Restoranlar</p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="con-text">
                        <div class="grid1-img">
                            <img src="~/web/images/flight.png" alt="">
                        </div>
                        <div class="grid1-desc">
                            <p>Uçuşlar</p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="con-text">
                        <div class="grid1-img">
                            <img src="~/web/images/group.png" alt="">
                        </div>
                        <div class="grid1-desc">
                            <p>Yapılacaklar</p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="con-text">
                        <div class="grid1-img">
                            <img src="~/web/images/key.png" alt="">
                        </div>
                        <div class="grid1-desc">
                            <p>Tatil Kiraları</p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="header_bottom_right_images">

                    <div class="slider" style="width:650px;height:400px;">
                        <ul class="rslides" id="slider1">
                            @foreach (var item in Model)
                            {
                                <li><img src="@item.BlogImage" alt="" style="width:650px;height:400px;"></li>
                            }
                            @*<li><img src="~/web/images/img2.jpg" alt=""></li>
                                <li><img src="~/web/images/img3.jpg" alt=""></li>
                                <li><img src="~/web/images/img4.jpg" alt=""></li>*@
                        </ul>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="wrap">
    <div class="wrapper">
        <div class="con-top">
            <h3>Seyahat Tatil Bloguma Hoşgeldiniz!</h3>
            <p>
                Merhaba ve "Kolay Yolculuk" blogumuza hoş geldiniz! Seyahat etmek, hayatın en büyüleyici deneyimlerinden biridir ve biz buradayız, dünya turu yaparken her adımınızı kolaylaştırmak için. "Kolay Yolculuk," seyahate olan tutkumuzu ve deneyimlerimizi paylaşmak, sizi dünya keşfinde daha güvenli ve keyifli bir şekilde yönlendirmek amacıyla yola çıktı.

                Bizimle birlikte, gezginlerin sıkça karşılaştığı sorunları çözmek, seyahat planlaması yaparken size rehberlik etmek ve dünya çapında benzersiz yerleri keşfetmek için kullanabileceğiniz pratik ipuçları sunuyoruz. Ayrıca, unutulmaz seyahat hikayeleri ve deneyimlerini paylaşarak sizi dünyayı keşfetmeye teşvik etmek istiyoruz.

                Seyahatinizi kolaylaştırmak ve daha fazla macera eklemek için size yardımcı olmak için buradayız. "Kolay Yolculuk" ile dünya turunuzu daha keyifli, sorunsuz ve unutulmaz hale getirin.

                Kolay Yolculuk'a hoş geldiniz ve dünya keşfinde size eşlik etmemize izin verin!
            </p>
        </div>

        <div class="grids">
            <div class="box1">
                
                @Html.Action("Partial1", "Default")
               
                @*<div class="padding">
                    <h4>Son 10 Blog</h4>
                    <ul class="list list-pad">
                        <li class="list-bg"><span>1.</span><a href="#">formas humanitatis pe</a></li>
                        <li class="list-bg1"><span>2.</span><a href="#">congue nihil imperdiet</a></li>
                        <li class="list-bg"><span>3.</span><a href="#">Aadipisicing elit sed do</a></li>
                        <li class="list-bg1"><span>4.</span><a href="#">luptatum zzril  </a></li>
                        <li class="list-bg"><span>5.</span><a href="#">Claritas est etiam</a></li>
                        <li class="list-bg1"><span>6.</span><a href="#">claritatem insitam;</a></li>
                        <li class="list-bg"><span>7.</span><a href="#">velit esse molestie consequa</a></li>
                        <li class="list-bg1"><span>8.</span><a href="#">nostrud exerci tation ulla</a></li>
                        <li class="list-bg"><span>9.</span><a href="#">demonstraverunt lectores</a></li>
                        <li class="list-bg1"><span>10.</span><a href="#">dolore te feu</a></li>
                    </ul>
                    <a href="#" class="link1">See all hotels</a>
                </div>*@

                @Html.Action("Partial2","Default")
                @*<div class="padding1">
                    <h4>En İyi Bloglar</h4>
                    <div class="box-left">
                        <div class="bot-img">
                            <img src="~/web/images/pic3.jpg" alt="" />
                        </div>
                        <div class="bot-desc">
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                        </div>
                        <div class="clear"></div>
                        <div class="bot-img">
                            <img src="~/web/images/pic7.jpg" alt="" />
                        </div>
                        <div class="bot-desc">
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                        </div>
                        <div class="clear"></div>
                        <div class="bot-img">
                            <img src="~/web/images/pic8.jpg" alt="" />
                        </div>
                        <div class="bot-desc">
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="box1-left">
                        <div class="bot-img">
                            <img src="~/web/images/pic9.jpg" alt="" />
                        </div>
                        <div class="bot-desc1">
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                        </div>
                        <div class="clear"></div>
                        <div class="bot-img">
                            <img src="~/web/images/pic10.jpg" alt="" />
                        </div>
                        <div class="bot-desc1">
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                        </div>
                        <div class="clear"></div>
                        <div class="bot-img">
                            <img src="~/web/images/pic3.jpg" alt="" />
                        </div>
                        <div class="bot-desc1">
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>*@
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

TravelTripProje/Views/Default/Partial1.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog>


<div class="padding">
    <h4>Son Bloglar</h4>
    <ul class="list list-pad">
        @{ int i = 0;}
        @foreach (var item in Model)
        {
            <li class="list-bg"><span>@{i++;} @i.</span><a href="/Blog/BlogDetay/@item.ID">@item.Baslik</a></li>
        }
    </ul>
    <a href="/Blog/Index" class="link1">Tümü Bloglar..</a>
</div>

TravelTripProje/Views/Default/Partial2.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog>
<div class="padding1">
    <h4>En Beğendiğim Yerler</h4>
    <div class="box-left">
        @foreach (var item in Model)
        {
            int uzun = @item.Aciklama.Length;
            <div class="bot-img">
                <img src="@item.BlogImage" alt="" />
            </div>
            <div class="bot-desc">
                <p>@item.Aciklama.Substring(0, uzun / 10)...</p>
            </div>
            <div class="clear"></div>
        }
    </div>
        @Html.Action("Partial3","Default")
</div>

TravelTripProje/Views/Default/Partial3.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog>
<div class="box1-left">
    @foreach (var item in Model)
    {
        int uzun = @item.Aciklama.Length;
        <div class="bot-img">
            <img src="@item.BlogImage" alt="" />
        </div>
        <div class="bot-desc">
            <p>@item.Aciklama.Substring(0, uzun / 10)...</p>
        </div>
        <div class="clear"></div>
    }
</div>